steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/grownome/shadow-cljs'
    args: ['compile', 'test']
  - name: 'gcr.io/cloud-builders/docker-compose'
    args: ['run','srv']


