version: '2.0'
services:
  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: db
  srv:
    image: node
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    entrypoint: node local/node-tests-ci.js
    environment:
        SQL_USER: myuser
        SQL_PASSWORD: mypass
        SQL_HOST: db
        SQL_NAME: db
